services:
  web:
    build: .
    ports:
      - "6000:6000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    env_file:
      - .env.example
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - app

  db:
    image: postgres:16
    restart: always
    env_file:
      - .env.example
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app

volumes:
  postgres_data:

networks:
  app:
    driver: bridge
